import http from "node:http";
import crypto from "node:crypto";
import { TelegramClient } from "teleproto";
import { StoreSession } from "teleproto/sessions/index.js";

const MAX_BODY=8192, LINK_TTL=600000, LOGIN_TTL=420000, RESEND_WAIT=15000;
const BOT="TelePilottBot";

function json(res,status,body,headers={}){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer",...headers});res.end(JSON.stringify(body));}
function html(res,status,body,nonce){res.writeHead(status,{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer","permissions-policy":"camera=(), microphone=(), geolocation=()","content-security-policy":`default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`});res.end(body);}
async function body(req){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>MAX_BODY)throw new Error("REQUEST_TOO_LARGE");chunks.push(c)}return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{};}
function cookies(req){const o={};for(const p of String(req.headers.cookie||"").split(";")){const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o;}
function eq(a,b){return /^[a-f0-9]{64}$/i.test(a||"")&&/^[a-f0-9]{64}$/i.test(b||"")&&crypto.timingSafeEqual(Buffer.from(a,"hex"),Buffer.from(b,"hex"));}
function phone(v){const p=String(v||"").trim().replace(/[\s()-]/g,"");return /^\+[1-9]\d{6,14}$/.test(p)?p:null;}
function msg(err){const e=String(err?.errorMessage||err?.message||"").toUpperCase();if(e.includes("PHONE_CODE_INVALID"))return"That code is incorrect. Use the newest code from Telegram.";if(e.includes("PHONE_CODE_EXPIRED"))return"That code expired. Start the login again.";if(e.includes("PASSWORD_HASH_INVALID"))return"That 2FA password is incorrect.";if(e.includes("PHONE_NUMBER_INVALID"))return"Telegram did not accept that phone number.";if(e.includes("SEND_CODE_UNAVAILABLE"))return"Telegram is not offering another delivery method right now. Check the Telegram app for the newest code.";if(e.includes("FLOOD"))return"Telegram temporarily limited login attempts. Please wait before trying again.";if(e.includes("AUTH_USER_CANCEL"))return"Login cancelled.";return"Telegram could not complete that step. Please try again.";}
function authErr(name){return Object.assign(new Error(name),{errorMessage:name});}

function page(nonce){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b1020"><title>TelePilot Connect</title><style>
:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(#0b1020,#111827,#0b1020);color:#f8fafc;display:grid;place-items:center;padding:24px}.w{width:min(100%,440px)}.brand{text-align:center;margin-bottom:18px}.logo{width:64px;height:64px;border-radius:21px;margin:auto;background:linear-gradient(145deg,#60a5fa,#7c3aed);display:grid;place-items:center;font-size:34px}.brand h1{margin:10px 0 3px}.brand p,.sub,.hint{color:#94a3b8}.card{background:#111827e8;border:1px solid #ffffff17;border-radius:24px;padding:22px}.step{display:none}.active{display:block}.ey{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#7f8da3}h2{margin:7px 0 8px;font-size:21px}.sub{line-height:1.45;margin:0 0 18px}input{width:100%;font-size:18px;padding:15px;border-radius:14px;border:1px solid #ffffff22;background:#070b14;color:white;outline:none}button{width:100%;border:0;border-radius:14px;padding:15px;margin-top:12px;font-size:16px;font-weight:700;color:white;background:linear-gradient(90deg,#3b82f6,#7c3aed)}button:disabled{opacity:.5}.secondary{background:#1e293b}.ghost{background:transparent;border:1px solid #ffffff17;color:#94a3b8}.err{min-height:20px;margin-top:10px;color:#fca5a5;font-size:14px}.note{min-height:20px;margin-top:10px;color:#93c5fd;font-size:13px}.hint{font-size:12px;margin-top:12px;line-height:1.4}.spin{width:34px;height:34px;border:3px solid #ffffff20;border-top-color:#60a5fa;border-radius:50%;animation:s 1s linear infinite;margin:10px auto 18px}@keyframes s{to{transform:rotate(360deg)}}.center{text-align:center}.pw{position:relative}.pw input{padding-right:72px}.show{position:absolute;right:7px;top:7px;width:auto;margin:0;padding:9px;background:#1e293b;font-size:13px}
</style></head><body><div class="w"><div class="brand"><div class="logo">✈️</div><h1>TelePilot Connect</h1><p>Connect your Telegram account</p></div><div class="card">
<section id="phone" class="step active"><div class="ey">Step 1</div><h2>Enter your phone number</h2><p class="sub">Use the number connected to the Telegram account you want TelePilot to use.</p><input id="phoneInput" type="tel" autocomplete="tel" inputmode="tel" placeholder="+___ __________"><button id="phoneBtn">Continue</button><div id="phoneErr" class="err"></div><div class="hint">Include + and the country code.</div></section>
<section id="waiting" class="step center"><div class="spin"></div><h2>Connecting to Telegram…</h2><p class="sub">This normally takes a few seconds.</p><button class="ghost cancel">Cancel</button></section>
<section id="code" class="step"><div class="ey">Step 2</div><h2>Verify your code</h2><p id="codeText" class="sub">Enter the newest code from Telegram.</p><input id="codeInput" inputmode="numeric" autocomplete="one-time-code" maxlength="12" placeholder="12345"><button id="codeBtn">Verify code</button><button id="smsBtn" class="secondary" disabled>Try SMS in 15s</button><button class="ghost cancel">Cancel</button><div id="smsNote" class="note"></div><div id="codeErr" class="err"></div><div class="hint">Telegram often sends the first login code inside the Telegram app instead of SMS.</div></section>
<section id="password" class="step"><div class="ey">Security check</div><h2>2-step verification</h2><p id="pwText" class="sub">This account has 2FA enabled.</p><div class="pw"><input id="pwInput" type="password" autocomplete="off" placeholder="Password"><button id="showPw" class="show" type="button">Show</button></div><button id="pwBtn">Continue</button><button class="ghost cancel">Cancel</button><div id="pwErr" class="err"></div></section>
<section id="email" class="step"><div class="ey">Telegram security</div><h2>Email verification</h2><p class="sub">Telegram requires an email address for this login.</p><input id="emailInput" type="email" autocomplete="email" placeholder="you@example.com"><button id="emailBtn">Continue</button><button class="ghost cancel">Cancel</button><div id="emailErr" class="err"></div></section>
<section id="email_code" class="step"><div class="ey">Telegram security</div><h2>Check your email</h2><p id="emailText" class="sub">Enter the verification code Telegram sent.</p><input id="emailCodeInput" inputmode="numeric" autocomplete="one-time-code" maxlength="16" placeholder="Code"><button id="emailCodeBtn">Verify email</button><button class="ghost cancel">Cancel</button><div id="emailCodeErr" class="err"></div></section>
<section id="done" class="step center"><div style="font-size:52px">✅</div><h2>Account connected</h2><p id="doneText" class="sub">You can return to TelePilot.</p><button id="returnBtn" class="secondary">Return to Telegram</button></section>
<section id="failed" class="step"><h2>Couldn’t connect</h2><p id="failText" class="sub">Please try again.</p><button id="retryBtn" class="secondary">Try again</button><button class="ghost back">Return to Telegram</button></section>
</div></div><script nonce="${nonce}">
const q=new URLSearchParams(location.search),auth={uid:q.get('uid'),exp:q.get('exp'),sig:q.get('sig')},$=id=>document.getElementById(id);let cur='phone',poll=null,smsTimer=null,smsAt=0,smsAsked=false;
function show(id){document.querySelectorAll('.step').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');cur=id}
async function post(url,data={}){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function countdown(sec){if(smsAsked)return;if(!smsAt)smsAt=Date.now()+sec*1000;clearInterval(smsTimer);const tick=()=>{const n=Math.max(0,Math.ceil((smsAt-Date.now())/1000));$('smsBtn').disabled=n>0;$('smsBtn').textContent=n?'Try SMS in '+n+'s':'📱 Didn’t get it? Try SMS';if(!n)clearInterval(smsTimer)};tick();smsTimer=setInterval(tick,500)}
async function status(){try{const r=await fetch('/api/login/status',{cache:'no-store'}),s=await r.json();if(!r.ok)return;if(s.step==='code'){show('code');$('codeText').textContent=s.viaApp?'Telegram sent the code inside your Telegram app. Enter the newest code below.':'Telegram sent a login code. Check SMS and Telegram, then enter the newest code.';$('codeErr').textContent=s.error||'';$('smsNote').textContent=s.notice||'';smsAsked=!!s.smsRequested;if(smsAsked){$('smsBtn').disabled=true;$('smsBtn').textContent='SMS fallback requested'}else if(!smsAt)countdown(s.resendAfterSeconds??15)}else if(s.step==='password'){show('password');$('pwText').textContent=s.hint?'2FA hint: '+s.hint:'This account has 2-step verification enabled.';$('pwErr').textContent=s.error||''}else if(s.step==='email'){show('email');$('emailErr').textContent=s.error||''}else if(s.step==='email_code'){show('email_code');$('emailText').textContent=s.emailPattern?'Telegram sent a code to '+s.emailPattern+'.':'Enter the verification code Telegram sent.';$('emailCodeErr').textContent=s.error||''}else if(s.step==='done'){clearInterval(poll);show('done');$('doneText').textContent=s.username?'Connected as @'+s.username+'. You can return to TelePilot.':'Your Telegram account is connected.'}else if(s.step==='failed'){clearInterval(poll);show('failed');$('failText').textContent=s.error||'Telegram could not complete the login.'}else if(!['phone','waiting'].includes(cur))show('waiting')}catch{}}
function startPoll(){clearInterval(poll);poll=setInterval(status,900);status()}
$('phoneBtn').onclick=async()=>{try{$('phoneErr').textContent='';await post('/api/login/start',{...auth,phone:$('phoneInput').value});show('waiting');startPoll()}catch(e){$('phoneErr').textContent=e.message}};
async function send(kind,input,err){try{$(err).textContent='';await post('/api/login/input',{kind,value:$(input).value});$(input).value='';show('waiting')}catch(e){$(err).textContent=e.message}}
$('codeBtn').onclick=()=>send('code','codeInput','codeErr');$('pwBtn').onclick=()=>send('password','pwInput','pwErr');$('emailBtn').onclick=()=>send('email','emailInput','emailErr');$('emailCodeBtn').onclick=()=>send('email_code','emailCodeInput','emailCodeErr');
$('smsBtn').onclick=async()=>{const b=$('smsBtn');b.disabled=true;$('smsNote').textContent='Requesting an SMS fallback from Telegram…';try{await post('/api/login/resend');smsAsked=true;b.textContent='SMS fallback requested';$('smsNote').textContent='Telegram was asked for an SMS fallback. Use the newest code that arrives.';show('waiting')}catch(e){$('smsNote').textContent=e.message;b.disabled=false;b.textContent='📱 Didn’t get it? Try SMS'}};
$('showPw').onclick=()=>{const i=$('pwInput'),x=i.type==='password';i.type=x?'text':'password';$('showPw').textContent=x?'Hide':'Show'};document.querySelectorAll('.cancel').forEach(b=>b.onclick=async()=>{try{await post('/api/login/cancel')}catch{}location.href='tg://resolve?domain=${BOT}'});document.querySelectorAll('.back').forEach(b=>b.onclick=()=>location.href='tg://resolve?domain=${BOT}');$('returnBtn').onclick=()=>location.href='tg://resolve?domain=${BOT}';$('retryBtn').onclick=()=>location.reload();if(!auth.uid||!auth.exp||!auth.sig){show('failed');$('failText').textContent='This connection link is invalid or expired.'}
</script></body></html>`;}

export function createConnectService({botToken,apiId,apiHash,getSessionName,publicUrl,onConnected}){
  const pending=new Map();
  const signature=(uid,exp)=>crypto.createHmac("sha256",botToken).update(`${uid}.${exp}.telepilot-connect-v2`).digest("hex");
  function makeConnectUrl(uid){const exp=Date.now()+LINK_TTL;return `${publicUrl}/connect?uid=${encodeURIComponent(uid)}&exp=${exp}&sig=${signature(uid,exp)}`}
  function verify(uid,expRaw,sig){const exp=Number(expRaw);return /^\d+$/.test(String(uid||""))&&Number.isFinite(exp)&&Date.now()<=exp&&exp-Date.now()<=LINK_TTL+30000&&eq(signature(uid,exp),String(sig||""));}
  function loginFor(req){const id=cookies(req).tp_login;return id?pending.get(id)||null:null}
  function wait(login,kind,meta={}){login.step=kind;login.error=login.nextError||null;login.nextError=null;Object.assign(login,meta);if(kind==='code')login.codeAt=Date.now();return new Promise((resolve,reject)=>{login.waiting={kind,resolve,reject}})}
  function stop(login,text){if(login.finished)return;login.finished=true;login.step='failed';login.error=text;if(login.waiting){login.waiting.reject(authErr('AUTH_USER_CANCEL'));login.waiting=null}void login.client.disconnect().catch(()=>{})}
  async function authorize(login){const p={phoneNumber:login.phone,forceSMS:false,phoneCode:via=>wait(login,'code',{viaApp:!!via}),password:hint=>wait(login,'password',{hint:hint||''}),emailAddress:()=>wait(login,'email'),emailVerification:async(o={})=>({type:'code',code:await wait(login,'email_code',{emailPattern:o.emailPattern||''})}),firstAndLastNames:async()=>{throw authErr('AUTH_USER_CANCEL')},onError:async e=>{const raw=String(e?.errorMessage||e?.message||'').toUpperCase();login.nextError=msg(e);return raw.includes('FLOOD')||raw.includes('PHONE_CODE_EXPIRED')||raw.includes('AUTH_USER_CANCEL')||raw.includes('SEND_CODE_UNAVAILABLE')}};login.params=p;try{await login.client.start(p);if(login.finished)return;const me=await login.client.getMe();login.finished=true;login.step='done';login.username=me?.username||'';login.waiting=null;await onConnected(login.uid,login.client,me)}catch(e){if(login.finished&&login.step==='failed')return;login.finished=true;login.step='failed';login.error=login.nextError||msg(e);login.waiting=null;try{await login.client.disconnect()}catch{}}}
  const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',publicUrl);if(req.method==='GET'&&u.pathname==='/')return json(res,200,{ok:true,service:'TelePilot Connect'});if(req.method==='GET'&&u.pathname==='/connect'){const uid=u.searchParams.get('uid'),exp=u.searchParams.get('exp'),sig=u.searchParams.get('sig'),nonce=crypto.randomBytes(18).toString('base64');return html(res,verify(uid,exp,sig)?200:403,page(nonce),nonce)}
    if(req.method==='POST'&&u.pathname==='/api/login/start'){const b=await body(req);if(!verify(b.uid,b.exp,b.sig))return json(res,403,{error:'This connection link expired. Open TelePilot and try again.'});const ph=phone(b.phone);if(!ph)return json(res,400,{error:'Enter your full phone number starting with + and the country code.'});for(const l of pending.values())if(String(l.uid)===String(b.uid)&&!l.finished)stop(l,'A newer login attempt was started.');const id=crypto.randomBytes(32).toString('hex'),sn=await getSessionName(String(b.uid)),client=new TelegramClient(new StoreSession(sn),apiId,apiHash,{connectionRetries:5}),l={id,uid:String(b.uid),phone:ph,client,step:'starting',error:null,nextError:null,notice:null,waiting:null,finished:false,username:'',params:null,codeAt:null,smsRequested:false};pending.set(id,l);setTimeout(()=>{if(!l.finished)stop(l,'This login attempt expired. Start again from TelePilot.');setTimeout(()=>pending.delete(id),60000)},LOGIN_TTL);void authorize(l);return json(res,200,{ok:true},{'set-cookie':`tp_login=${id}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.ceil(LOGIN_TTL/1000)}`})}
    if(req.method==='GET'&&u.pathname==='/api/login/status'){const l=loginFor(req);if(!l)return json(res,404,{error:'No active login.'});const elapsed=l.codeAt?Date.now()-l.codeAt:0;return json(res,200,{step:l.step,error:l.error,notice:l.notice,viaApp:!!l.viaApp,hint:l.hint||'',emailPattern:l.emailPattern||'',username:l.username||'',smsRequested:!!l.smsRequested,resendAfterSeconds:l.codeAt?Math.max(0,Math.ceil((RESEND_WAIT-elapsed)/1000)):15})}
    if(req.method==='POST'&&u.pathname==='/api/login/resend'){const l=loginFor(req);if(!l||l.finished)return json(res,409,{error:'This login is no longer active.'});if(!l.waiting||l.waiting.kind!=='code')return json(res,409,{error:'Wait until Telegram asks for the login code first.'});if(l.smsRequested)return json(res,409,{error:'SMS fallback was already requested for this login.'});const elapsed=Date.now()-Number(l.codeAt||Date.now());if(elapsed<RESEND_WAIT)return json(res,429,{error:`Please wait ${Math.ceil((RESEND_WAIT-elapsed)/1000)} more seconds before requesting SMS.`});if(!l.params)return json(res,409,{error:'Telegram login is not ready to resend yet.'});l.smsRequested=true;l.notice='Telegram was asked for an SMS fallback. Use the newest code that arrives.';l.params.forceSMS=true;const {reject}=l.waiting;l.waiting=null;l.step='working';l.error=null;reject(authErr('RESTART_AUTH'));return json(res,200,{ok:true})}
    if(req.method==='POST'&&u.pathname==='/api/login/input'){const l=loginFor(req);if(!l||l.finished)return json(res,409,{error:'This login is no longer active.'});const b=await body(req),kind=String(b.kind||''),raw=String(b.value??''),value=kind==='password'?raw:raw.trim();if(!l.waiting||l.waiting.kind!==kind)return json(res,409,{error:'Telegram is not waiting for that step yet.'});if(!value||value.length>256)return json(res,400,{error:'Enter a valid value.'});const {resolve}=l.waiting;l.waiting=null;l.step='working';l.error=null;resolve(value);return json(res,200,{ok:true})}
    if(req.method==='POST'&&u.pathname==='/api/login/cancel'){const l=loginFor(req);if(l&&!l.finished)stop(l,'Login cancelled.');return json(res,200,{ok:true},{'set-cookie':'tp_login=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'})}
    return json(res,404,{error:'Not found'});
  }catch(e){console.error('TelePilot web service error:',e?.message||e);if(String(e?.message||'')==='REQUEST_TOO_LARGE')return json(res,413,{error:'Request too large'});return json(res,500,{error:'TelePilot hit an unexpected error.'})}});
  return {makeConnectUrl,listen(port){server.listen(port,'0.0.0.0',()=>console.log(`TelePilot Connect listening on port ${port}`))}};
}
